---
 - name: Installing and Launch Filebeat
   hosts: webservers
   become: yes
   tasks:
     #Use a command module
    - name: Download metricbeat.deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    - name: Install metricbeat.deb file
      command: dpkg -i metricbeat-7.4.0-amd64.deb

    - name: Drop in metricbeat.yml
      copy:
        src: /etc/ansible/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and Configure System Module
      command: metricbeat modules enable docker

    - name: Setup metricbeat
      command: metricbeat setup

    - name: Enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes

    - name: Log metricbeat to stderr and disables syslog/file output
      command: metricbeat -e
